### ISSUE TITLE
QDP interface and copy_gauge_inc.cu

### ISSUE THREAD

**Issue by walkloud** [lattice/quda#1325]
When `QUDA_INTERFACE_QDP=OFF` at compilation, it seems that `copy_gauge_inc` is not built.  This does not seem like expected behavior.  ERROR below.

```
ERROR: QDP interface has not been built
 (rank 0, host lassen16, copy_gauge_inc.cu:196 in void quda::copyGauge(quda::GaugeField&, const quda::GaugeField&, QudaFieldLocation, FloatOut*, FloatIn*, FloatOut**, FloatIn**, int) [with FloatOut = double; FloatIn = double; int length = 18; QudaFieldLocation = QudaFieldLocation_s]())
       last kernel called was (name=cudaMemcpyDefault,volume=bytes=9437184,aux=copy,cuda_gauge_field.cpp,576)
```

**Comment by maddyscientist** [comment]
This is the expected behavior.  Enabling the interfaces (QDP, MILC, CPS, etc.) enables compilation of copy kernels for the various data orders that these frameworks / applications use.  Even if you’re not using one of these names frameworks, you may still be relying on the interface enablement if you use this corresponding data order.  The built in tests for example, use a mixture of MILC and QDP ordering and so require them to be enabled.
