### ISSUE TITLE
cray and GPU_COMMS active

### ISSUE THREAD

**Issue by nmrcardoso** [lattice/quda#197]
In cray system with  cuda 5.5, GPU_COMMS active and MPICH_RDMA_ENABLED_CUDA=1
quda fails with
ERROR: (CUDA) cannot set while device is active in this process
if "cudaSetDeviceFlags(cudaDeviceMapHost);" is commented in interface_quda.cpp, then there is no problem.

    #ifdef GPU_COMMS
    int mpich_rdma_flag = getenv("MPICH_RDMA_ENABLED_CUDA")==NULL?0:atoi(getenv ("MPICH_RDMA_ENABLED_CUDA"));
    if(mpich_rdma_flag != 1){
        if(deviceProp.canMapHostMemory) cudaSetDeviceFlags(cudaDeviceMapHost);
    }
    #else
    if(deviceProp.canMapHostMemory) cudaSetDeviceFlags(cudaDeviceMapHost);
    #endif

**Comment by mathiaswagner** [comment]
I saw that with `GPU_COMMS=no` setting in a run on 8 GPUs.
```
ERROR: (CUDA) cannot set while device is active in this process (rank 0, host nid11400, interface_quda.cpp:387 in initQudaDevice())
       last kernel called was (name=,volume=,aux=)
```

I am

**Comment by mathiaswagner** [comment]
Newer CUDA versions have `cudaGetDeviceFlags` that we could use to query flags before setting them but that is not in CUDA 5.5 which is currently default on the Cray.

**Comment by mathiaswagner** [comment]
I just checked on the NCSA testbed for CUDA 6.5 and the error is not dependent on the CUDA version.

**Comment by mikeaclark** [comment]
Mathias can you clarify the problem you saw with `GPU_COMMS = no` on 8 GPUs?  It looks like your comment was truncated at the end.

**Comment by mathiaswagner** [comment]
I found a rather old technical note http://www.cfi.ses.ac.uk/cfi/files/2014/06/GPUDirect1.pdf that (and I assume the part I am referring to still applies) confirms that CUDA aware MPI creates the CUDA context when MPI_Init is called:

*GPU Affinity: When multiple GPUs are present on a node, users might want to set the MPI process affinity to a particular GPU using cuda calls like cudaSetDevice(). This can be done after MPI_Init based on MPI rank of the process. But MVAPICH2 performs some cuda operations like buffer registration and others during MPI_Init which result in default context creation. Hence, setting GPU Affinity after MPI_Init could create issues due to the context switch. 
...*
(page 11)

I don't know whether this also happens with OpenMPI / MVAPICH.

**Comment by mathiaswagner** [comment]
Sorry, I don't know what I wanted to say there. To cut it short: The current interface_quda.cpp calls `
```
  // if the device supports host-mapped memory, then enable this
#ifndef USE_QDPJIT
  if(deviceProp.canMapHostMemory) cudaSetDeviceFlags(cudaDeviceMapHost);
  checkCudaError();
#endif
``` 
around line 387 in `initQudaDevice`. As MPI_Init is called before we do `initQudaDevice` the MPI aware CUDA creates a CUDA context and the call to ` cudaSetDeviceFlags` triggers an error as expected.

**Comment by mikeaclark** [comment]
It was because MPI created the CUDA context that I introduced the separate initQudaDevice / initQudaMemory functions to work around this issue.  So instead of:
```
MPI_Init();
initQuda();
```
you do
```
initQudaDevice();
MPI_Init();
initQudaMemory();
```
I found this to work fine on Cray MPI / MVAPICH2 / OpenMPI.  However, recent MVAPICH / OpenMPI releases did away with the restriction of creating the CUDA context during MPI_Init allowing for the normal initialization flow.  It's disappointing to hear that Cray MPI still hasn't been updated as such.

So the choices are:
1. Use a recent MVAPICH2 / OpenMPI
2. Don't use GPU_COMMS
3. Rewrite the wrapper code to split QUDA initialization

**Comment by mikeaclark** [comment]
Moreover, the split initialization is much more invasive to legacy code and requires that the device ordinal is set prior to the MPI rank being known, so it's much more messy.  That's why I haven't pushed on this, since I thought the MPI libraries has all caught up.

**Comment by mikeaclark** [comment]
And Mathias, to your problem where the issue arose even though `GPU_COMMS = no`, I guess in that case you had enabled GPU-aware MPI with `MPICH_RDMA_ENABLED_CUDA=1` even though you weren't using it?

**Comment by mathiaswagner** [comment]
Yes. That was implied in my comment.

**Comment by mikeaclark** [comment]
I'm checking into this, but I it might be the case that this API call is unnecessary on modern versions of CUDA and Fermi and later GPUs.  Hopefully this will be the case, it is an easy fix for Cray MPI.  The device ordinal issue is not a problem on the Crays, since all Cray systems this affects (XK6 / XK7 / XC30) have only one GPU per node.

**Comment by mathiaswagner** [comment]
I am not sure whether this is necessary. My try to get the device flags didn't work as the function is not there in CUDA 5.5.

Apart from that: My error occurred from MILC and the milc_interface uses `initQuda` and not the separate calls.

**Comment by mikeaclark** [comment]
My point is that if this is a simple fix (removing the call to `cudaSetDeviceFlags(cudaDeviceMapHost);`), then we can continue to use `initQuda` without fear on all platforms.  Note that this issue is essentially the same as using QDP_JIT with QUDA (which also creates the CUDA context) which is why there is the QDP_JIT guard around this function.

**Comment by mathiaswagner** [comment]
I am not sure since when this is in the documentation, but

*cudaDeviceMapHost: This flag enables allocating pinned host memory that is accessible to the device. It is implicit for the runtime but may be absent if a context is created using the driver API. If this flag is not set, cudaHostGetDevicePointer() will always return a failure code.*

**Comment by mathiaswagner** [comment]
So, if there is no context we can successfully call `cudaSetDeviceFlags(cudaDeviceMapHost)` but don't need it as we create the context using the runtime API ???

**Comment by mikeaclark** [comment]
I think this is safe to delete then.  Aren't these the only possibilities:
* Call initQuda() normally, this creates the CUDA context using the runtime API.  API call not needed.
* Call initQuda() after MPI library has created the context using runtime API.  (This will break if we try to change the CUDA device.)  API call not needed.  
* Call initQuda() after MPI library has created the context using driver API.  (This will break if we try to change the CUDA device.)  API call is not needed since the MPI library will call this cudaDeviceMapHost since this is needed for GPU-aware MPI.

**Comment by mathiaswagner** [comment]
I created pull request #245 for this. I don't see any need to have this call as it will only create issues if the context is already created and have no impacted if the context is created from within QUDA.

**Comment by mikeaclark** [comment]
I've merged this pull request, which closes this bug.
