### ISSUE TITLE
Kernels that use the RNG class are not reproducible when autotuning

### ISSUE THREAD

**Issue by mikeaclark** [lattice/quda#349]
I noticed when running the gauge_alg_test that the answer changes for the first test depending on whether autotuning is occurring.  This is because the state of the RNG generator is not being restored after the tuning has completed, giving a different answer if the tuning is disabled or if it has already previously been performed.  This affects the heatbath algorithm and the creation of an initial hot state.

We should restore the initial RNG state to ensure reproducibility regardless of whether autotuning is occurring or not.

@nmrcardoso can you take a look at this?  Since you wrote the RNG class, I think you are likely the best person to do this.

**Comment by nmrcardoso** [comment]
I have almost this implemented, not yet put this hotfix in git due a minor problem, see bellow.
After some runs and without getting the desire results, I found that the unitarize links also needs to have a backup/restore gauge field in the tuning process if we use the same gauge field for the the input and the output , otherwise we cannot get the same results :S

@mikeaclark, can I remove the const from "cudaGaugeField &input" in order to make the restore working for the input gauge field, since the restore cannot be made over a const or there are a better way?

**Comment by mikeaclark** [comment]
I have the unitarize problem fixed already on my feature/gauge_reduce branch.  Feel free to put your fix in my branch.

This branch gets rid of the need for atomicAdd, replacing it with a reduction by the last thread block.  This makes the plaquette computation much faster (now runs over 1 TFLOPS on a Maxwell GPU), and I've applied this to the gauge fixing kernels as well.  There is also a further speed boost for single-precision gauge::FloatNOrder with reconstruct-8.

**Comment by nmrcardoso** [comment]
Thanks @mikeaclark , that's really great news :)
I already updated and tested the backup/restore option in the kernels that uses the RNG.
