### ISSUE TITLE
redirection to master branch

### ISSUE THREAD

**Issue by alexstrel** [lattice/quda#360]
the official site http://lattice.github.io/quda/ redirects now to the develop branch (instead of master, as it should).

**Comment by mathiaswagner** [comment]
The default branch is set to develop. According to github that means that newly created pull requests are targeted for merging into develop. Seems like that makes develop the selected branch when following the link. Not sure how to change that.

**Comment by mathiaswagner** [comment]
We could set the link from the page to https://github.com/lattice/quda/tree/master

**Comment by mikeaclark** [comment]
I set the default branch to develop as it means that pull requests automatically go to this branch instead of to master.  It also means that the network defaults to focus on the last commit to develop which is typically much more recent than master, which can lag behind months and months.

If want to reset the default branch to master, then it can be done so here:
https://github.com/lattice/quda/settings/branches

I like @mathiaswagner's suggestion of pointing to https://github.com/lattice/quda/tree/master instead though, keeping the default branch at develop.

Thoughts?

**Comment by mathiaswagner** [comment]
I think we should just point to the master branch. I like develop being the pre-selected branch for pull requests. If there are no objections I will update the link on the webpage.

**Comment by mikeaclark** [comment]
Sounds good to me.

**Comment by mathiaswagner** [comment]
Fixed with 484efebd0a81e7efbb7a04a868b5536fcc71cdec
