### ISSUE TITLE
TRLM failure for full matrix mobius solves

### ISSUE THREAD

**Issue by cpviolator** [lattice/quda#972]
In the present state, the TRLM will fail to find solutions to the full matrix problem with mobius. Conversely, TRLM will solve the EO preconditioned system very well.

**Comment by cpviolator** [comment]
Update: The unpreconditioned system is pretty poorly conditioned. Even a Simple CG takes an unreasonable number of iterations to converge. It is likely that TRLM is experiencing similar issues due to the same poor condition number.

**Comment by weinbe2** [comment]
@cpviolator do you have an `invert_test` repro for this? I'm a little surprised TRLM is failing on the full problem but not the EO system. EO normally only buys you a factor of 2 on the condition number, which isn't nothing, but shouldn't be the life-or-death difference.

**Comment by cpviolator** [comment]
@weinbe2 Sure thing. Summit is crammed at the moment, I'll get a reproducer ASAP.

**Comment by weinbe2** [comment]
@cpviolator no rush, I won't be able to get to it exceptionally quickly.

**Comment by maddyscientist** [comment]
This issue can stay closed.  The issue with full Mobius taking an aeon to converge is not related to the Eigen solver.

@weinbe2 to see the issue @cpviolator is talking about just compare CG with and with e/o preconditioning.  Can be > 10x iteration difference.  I suspect it's just because one is running with a random lattice gives this and not related to reality.  Same experiment should be done with a real lattice.  Until we see otherwise, I think there's no bug here.

**Comment by weinbe2** [comment]
@maddyscientist fair enough re:closing it as a bug.
